/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GameCard: typeof import('./../components/vp/GameCard.vue')['default']
    ICarbonRepeatOne: typeof import('~icons/carbon/repeat-one')['default']
    Modal: typeof import('./../components/modal/Modal.vue')['default']
    T: typeof import('./../components/vp/T.vue')['default']
  }
}
