/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GameCard: typeof import('./../components/Card/GameCard.vue')['default']
    T: typeof import('./../components/T.vue')['default']
  }
}
